version: '3.1'

services:
  api:
    tty: true
    stdin_open: true
    container_name: stock-trade-api
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
